# Generated by Django 2.2.12 on 2020-06-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_cdn', '0002_auto_20200531_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageurl',
            name='height',
            field=models.PositiveIntegerField(default=0, verbose_name='Height'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageurl',
            name='width',
            field=models.PositiveIntegerField(default=0, verbose_name='Width'),
            preserve_default=False,
        ),
    ]
