# Generated by Django 2.2.13 on 2020-06-06 12:53

from django.db import migrations, models

import forum.utils.dbfields


class Migration(migrations.Migration):

    dependencies = [
        ('forum_cdn', '0003_auto_20200604_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='IframelyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_src', models.URLField(max_length=512, verbose_name='Original source')),
                ('src_hash', forum.utils.dbfields.Sha512Field(max_length=64, verbose_name='SHA512 hash of orig_src')),
                ('accessed_at', models.DateTimeField(verbose_name='Accessed at')),
                ('response_code', models.PositiveSmallIntegerField(verbose_name='HTTP response code')),
                ('response_json', models.TextField(verbose_name='JSON response')),
            ],
            options={
                'verbose_name': 'ImageUrl',
                'verbose_name_plural': 'ImageUrls',
            },
        ),
        migrations.AddIndex(
            model_name='iframelyresponse',
            index=models.Index(fields=['accessed_at'], name='accessedat'),
        ),
        migrations.AddConstraint(
            model_name='iframelyresponse',
            constraint=models.UniqueConstraint(fields=('src_hash',), name='srchash'),
        ),
    ]
