# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_cdn', '0014_auto_20151018_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageurl',
            name='orig_src',
            field=models.URLField(max_length=512, verbose_name='Original source'),
        ),
    ]
