language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r backend/requirements.txt
  - pip install coveralls
# command to run tests
script:
  pytest
after_success:
  coveralls
