language: python
addons:
  mariadb: 10.0
cache:
  bundler: true
  pip: true
  directories:
    - frontend/node_modules
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r backend/requirements.txt
  - pip install coveralls
# command to run tests
script:
  - tools/run-linter-and-isort.sh
  - tools/run-tests-with-coverage.sh
after_success:
  coveralls
