dist: trusty
language: python
addons:
  mariadb: 10.0
cache:
  bundler: true
  pip: true
  directories:
    - node_modules
node_js: 6
python:
  - 3.5
  - 3.6
# command to install dependencies
install:
  - pip install -r backend/requirements.txt
  - npm i
  - gulp build
  - pip install coveralls
# command to run tests
script:
  - tools/run-linter-and-isort.sh
  - tools/run-tests-with-coverage.sh
after_success:
  coveralls
