# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 14:16
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_base', '0031_auto_20151020_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-time',)},
        ),
        migrations.AlterField(
            model_name='comment',
            name='prev_comment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='answer_set', to='forum_base.Comment', verbose_name='Answered comment'),
        ),
    ]
