# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_base', '0032_auto_20160911_1416'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='comment',
            index_together=set([('topic', 'time')]),
        ),
    ]
