# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 21:14
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_cdn', '0015_auto_20170101_1228'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum_base', '0035_auto_20170112_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroductionModification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(help_text='Quote (visible in the tooltip of the username)', max_length=256, verbose_name='Chosen quote')),
                ('introduction_md_all', models.TextField(help_text='Introduction in Markdown format (visible for everyone)', verbose_name='Introduction for everybody (MD)')),
                ('introduction_md_reg', models.TextField(help_text='Introduction in Markdown format (visible for registered users only)', verbose_name='Introduction for registered users (MD)')),
                ('introduction_md_friends', models.TextField(help_text='Introduction in Markdown format (visible only for users marked as friends)', verbose_name='Introduction for friended users (MD)')),
                ('images', models.ManyToManyField(to='forum_cdn.Image', verbose_name="Images in this user's descriptions")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Respective user')),
            ],
            options={
                'verbose_name_plural': 'Settings modifications',
                'verbose_name': 'Settings modification',
            },
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'User setting', 'verbose_name_plural': 'User settings'},
        ),
        migrations.AlterField(
            model_name='settings',
            name='introduction_html_all',
            field=models.TextField(help_text='Introduction in HTML format (visible for everyone)', verbose_name='Introduction for everybody (HTML)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='introduction_html_friends',
            field=models.TextField(help_text='Introduction in HTML format (visible only for users marked as friends)', verbose_name='Introduction for friended users (HTML)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='introduction_html_reg',
            field=models.TextField(help_text='Introduction in HTML format (visible for registered users only)', verbose_name='Introduction for registered users (HTML)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='introduction_md_all',
            field=models.TextField(help_text='Introduction in Markdown format (visible for everyone)', verbose_name='Introduction for everybody (MD)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='introduction_md_friends',
            field=models.TextField(help_text='Introduction in Markdown format (visible only for users marked as friends)', verbose_name='Introduction for friended users (MD)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='introduction_md_reg',
            field=models.TextField(help_text='Introduction in Markdown format (visible for registered users only)', verbose_name='Introduction for registered users (MD)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='quote',
            field=models.CharField(help_text='Quote (visible in the tooltip of the username)', max_length=256, verbose_name='Chosen quote'),
        ),
    ]
