# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 14:32
from __future__ import unicode_literals

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150, verbose_name='Text')),
                ('votes', models.PositiveIntegerField(verbose_name='Vote count')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Order ID')),
            ],
            options={
                'verbose_name_plural': 'Choices',
                'verbose_name': 'Choice',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('text',), primary_key=True, serialize=False, unique=True, verbose_name='Slug')),
                ('text', models.CharField(max_length=150, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('topic', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum_base.Topic', verbose_name='In topic')),
            ],
            options={
                'verbose_name_plural': 'Questions',
                'verbose_name': 'Question',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Last modified at')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_poll.Choice', verbose_name='Choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_poll.Question', verbose_name='Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Votes',
                'verbose_name': 'Vote',
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_poll.Question', verbose_name='Question'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('user', 'question')]),
        ),
    ]
