# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 19:25
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum_cdn', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('is_enabled', models.BooleanField(verbose_name='Is enabled')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('content_html', models.TextField(verbose_name='HTML content')),
                ('content_md', models.TextField(verbose_name='Markdown content')),
                ('images', models.ManyToManyField(to='forum_cdn.Image', verbose_name='Images in this global message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Global message',
                'verbose_name_plural': 'Global messages',
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(max_length=10, null=True, verbose_name='Thread ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('opened_at', models.DateTimeField(null=True, verbose_name='Read at')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Unread'), (2, 'Read'), (3, 'Deleted'), (4, 'Replied')], default=1, verbose_name='Status')),
                ('is_forwarded', models.BooleanField(default=False, verbose_name='Is forwarded')),
                ('is_retained_sender', models.BooleanField(default=False, verbose_name="Retained in sender's outbox")),
                ('is_retained_recipient', models.BooleanField(default=False, verbose_name="Retained in recipient's inbox")),
                ('sender_deleted', models.BooleanField(default=False, verbose_name='Sender deleted it in outbox')),
                ('content_html', models.TextField(verbose_name='HTML content')),
                ('content_md', models.TextField(verbose_name='Markdown content')),
                ('images', models.ManyToManyField(to='forum_cdn.Image', verbose_name='Images in this mail message')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_recipient', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_sender', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Mail message',
                'verbose_name_plural': 'Mail messages',
            },
        ),
    ]
