# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 15:40
from __future__ import unicode_literals

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum_base', '0001_initial'),
        ('forum_cdn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('name',), primary_key=True, serialize=False, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated at')),
                ('ends_at', models.DateTimeField(verbose_name='Ends at')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Running'), (2, 'Finished'), (3, 'Archived')], default=0, verbose_name='Status')),
                ('content_html', models.TextField(verbose_name='HTML content')),
                ('content_md', models.TextField(verbose_name='Markdown content')),
                ('images', models.ManyToManyField(to='forum_cdn.Image', verbose_name='Images in this project description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('related_topic', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum_base.Topic', verbose_name='Related topic')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectBacker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated at')),
                ('content_html', models.TextField(verbose_name='HTML content')),
                ('content_md', models.TextField(verbose_name='Markdown content')),
                ('images', models.ManyToManyField(to='forum_cdn.Image', verbose_name="Images in this backer's message")),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_crowdfunding.Project', verbose_name='Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Backer')),
            ],
            options={
                'verbose_name': 'Project backer',
                'verbose_name_plural': 'Project backers',
            },
        ),
        migrations.AlterUniqueTogether(
            name='projectbacker',
            unique_together=set([('project', 'user')]),
        ),
    ]
