# Generated by Django 2.2.9 on 2019-12-23 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum_base', '0001_initial'),
        ('forum_cdn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=100, populate_from=('name',), unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('place', models.CharField(max_length=100, verbose_name='Place')),
                ('date_start', models.DateField(verbose_name='Start date')),
                ('date_end', models.DateField(verbose_name='End date')),
                ('is_enabled', models.BooleanField(default=False)),
                ('content_html', models.TextField(verbose_name='HTML content')),
                ('content_md', models.TextField(verbose_name='Markdown content')),
                ('images', models.ManyToManyField(to='forum_cdn.Image', verbose_name="Images in this event's description")),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum_base.Topic', verbose_name='Related topic')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='EventResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified at')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Unanswered'), (1, 'Going'), (2, 'Maybe going'), (3, 'Not going'), (4, 'Ignored')], default=0, verbose_name='Response')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_event.Event', verbose_name='Event')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_responses', to=settings.AUTH_USER_MODEL, verbose_name='Invitee')),
                ('inviter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_sharings', to=settings.AUTH_USER_MODEL, verbose_name='Inviter')),
            ],
            options={
                'verbose_name': 'Event response',
                'verbose_name_plural': 'Event responses',
                'unique_together': {('event', 'invitee')},
            },
        ),
    ]
